name: prueba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  geolocator: ^13.0.2
  get_it: ^8.0.3
  http: ^1.3.0
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/desconocido.png